### ISSUE TITLE
Error when spinning up the project

### ISSUE THREAD

**Issue by johnraygarcia** [aoudiamoncef/ubuntu-sshd#1]
Hi. First of all thank you for making this project. 
While trying it out I receive the following error message:

docker run -d -p 2222:22 -e SSH_USERNAME=ansible -e PASSWORD=ansible -e AUTHORIZED_KEYS="$(cat ~/.ssh/id_rsa.pub)" my-ubuntu-sshd:latest

>>> exec /usr/local/bin/configure-ssh-user.sh: no such file or directory

Looks like that file is not coppied into the container after this command in the Dockerfile:

>>> COPY configure-ssh-user.sh /usr/local/bin/

**Comment by aoudiamoncef** [comment]
Hi, have tried to build the docker image locally to see if you have the same error ?
